// let maVariable= 10;
// let typeDeVariable= typeof maVariable;
// alert(typeDeVariable);


// let humeur = prompt("comment cv?");
// let prenom = prompt("ton nom");
// let phrase = 'salut '+ prenom +' tu vas ' + humeur+'?';
// alert(phrase)
console.log("msg de bienvenur");
alert("bien ou koi");

console.log("user entre nombre");
let nombreUn =   prompt("entre un nombre");

console.log("user entre second nombre");
let nombreDeux =   prompt("encore un autre");

console.log("resultat en cours ...")
let resultat = Number (nombreUn) + Number  (nombreDeux);

console.log("le resultat" +  resultat)
alert(resultat);